import React from 'react';
import { Proposal, AgencySettings } from '../../types';
import { BlackEdition } from './templates/BlackEdition';
import { CinematicEdition } from './templates/CinematicEdition';
import { ExecutiveClean } from './templates/ExecutiveClean';
import { CorporateGold } from './templates/AutoGenerated/CorporateGold';
import { LuxuryExecutive } from './templates/LuxuryExecutive';


// Contract for all PDF templates (Stability Engine)
export interface TemplateProps {
    proposal: Proposal;
}

// 1. TEMPLATE_REGISTRY Centralizado
export type TemplateId = string;

export const TEMPLATE_REGISTRY: Record<string, React.FC<TemplateProps>> = {
    'black-edition': BlackEdition,
    'cinematic-edition': CinematicEdition,
    'executive-clean': ExecutiveClean,
    'corporate-gold': CorporateGold,
    'luxury-executive': LuxuryExecutive,
};


// Tool to get label for UI
export const getTemplateLabel = (id: string) => {
    switch (id) {
        case 'black-edition': return 'Black Edition';
        case 'cinematic-edition': return 'Cinematic Edition';
        case 'executive-clean': return 'Executive Clean';
        case 'corporate-gold': return 'Corporate Gold';
        case 'luxury-executive': return 'Luxury Executive';
        default: return id;

    }
};

// 2. DYNAMIC LAYOUT INTELLIGENCE (DLI) - IA Choice Logic com Configuração
export const getAIChoice = (proposal: Proposal, settings: AgencySettings): TemplateId => {
    const ticketSize = proposal.total || 0;
    const projectLower = (proposal.projectName || '').toLowerCase();
    const rules = settings.templateRules || [];

    // Filtra apenas regras ativas
    const activeRules = rules.filter(r => r.enabled);

    // 1. Procura por match exato de palavra-chave (Prioridade 1)
    for (const rule of activeRules) {
        if (rule.keywords.some(kw => projectLower.includes(kw.toLowerCase()))) {
            console.log(`[DLI] Match de palavra-chave: ${rule.templateId}`);
            return rule.templateId;
        }
    }

    // 2. Procura por Ticket Médio (Prioridade 2 - do maior para o menor)
    const sortedByTicket = [...activeRules].sort((a, b) => b.minTicket - a.minTicket);
    for (const rule of sortedByTicket) {
        if (ticketSize >= rule.minTicket && rule.minTicket > 0) {
            console.log(`[DLI] Match de Ticket Médio: ${rule.templateId}`);
            return rule.templateId;
        }
    }

    // 3. Fallback Padrão
    return 'executive-clean';
};

// 3. HYBRID SELECTION LOGIC (Manual Choice > AIChoice)
export const resolveTemplate = (proposal: Proposal, settings: AgencySettings) => {
    // 3.1 MANUAL OVERRIDE (ManualChoice) com Prioridade Máxima
    if (proposal.templateId && TEMPLATE_REGISTRY[proposal.templateId]) {
        return proposal.templateId;
    }

    // 3.2 SELEÇÃO AUTOMÁTICA (AIChoice)
    return getAIChoice(proposal, settings);
};

interface DynamicProposalRendererProps {
    proposal: Proposal;
    settings: AgencySettings;
}

export const DynamicProposalRenderer: React.FC<DynamicProposalRendererProps> = ({ proposal, settings }) => {
    const resolvedId = resolveTemplate(proposal, settings);
    const TemplateComponent = TEMPLATE_REGISTRY[resolvedId] || ExecutiveClean;

    return <TemplateComponent proposal={proposal} />;
};

export const registerAutoTemplate = (id: string, _component: React.FC<TemplateProps>) => {
    console.log(`[Stability Engine] Novo template registrado no DLI: ${id}`);
};
