import React, { useState, useEffect } from 'react';
import { useAppContext } from '../context/AppContext';
import { Proposal } from '../types';
import { BlackEdition } from '../components/pdf/templates/BlackEdition';
import { CinematicEdition } from '../components/pdf/templates/CinematicEdition';
import { ExecutiveClean } from '../components/pdf/templates/ExecutiveClean';
import { CorporateGold } from '../components/pdf/templates/AutoGenerated/CorporateGold';
import { resolveTemplate } from '../components/pdf/TemplateManager';
import { ArrowLeft, Sparkles, Layout, Monitor, Printer } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TestPreview: React.FC = () => {
    const { proposals, agencySettings } = useAppContext();
    const [selectedProposal, setSelectedProposal] = useState<Proposal | null>(null);
    const [previewMode, setPreviewMode] = useState<'all' | 'black' | 'cinematic' | 'executive' | 'corporate'>('all');
    const navigate = useNavigate();

    useEffect(() => {
        if (proposals.length > 0) {
            setSelectedProposal(proposals[0]);
        } else {
            // Mock para quando não há propostas no Firestore
            setSelectedProposal({
                id: 'mock-id',
                clientName: 'Cliente Exemplo Orbit',
                projectName: 'Projeto Corporate Audiovisual',
                clientEmail: 'cliente@exemplo.com',
                clientDocument: '000.000.000-00',
                status: 'draft',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                services: [
                    { id: '1', name: 'Produção Cinematográfica', description: 'Gravação 4K', price: 55000, quantity: 1 }
                ],
                total: 55000,
                templateId: '',
                terms: '50% sinal',
                notes: '',
                media: [],
                timeline: [],
                views: 0
            } as any);
        }
    }, [proposals]);

    if (!selectedProposal) {
        return (
            <div className="p-20 text-center">
                <div className="w-12 h-12 border-4 border-black border-t-transparent rounded-full animate-spin mx-auto shadow-2xl"></div>
                <p className="mt-4 text-neutral-500 font-bold uppercase tracking-widest text-xs">Nenhuma proposta para testes encontrada...</p>
            </div>
        );
    }

    const dliSuggested = resolveTemplate(selectedProposal, agencySettings);

    return (
        <div className="min-h-screen bg-[#f0f0f3] p-8 flex flex-col font-sans overflow-auto">
            {/* Header de Controle */}
            <div className="max-w-[1200px] mx-auto w-full mb-8 flex flex-col md:flex-row justify-between items-center bg-white p-6 rounded-3xl shadow-xl border border-white/40 gap-6">
                <div className="flex items-center gap-4">
                    <button
                        onClick={() => navigate('/proposals')}
                        className="p-3 bg-neutral-100 rounded-2xl hover:bg-black hover:text-white transition-all shadow-inner"
                    >
                        <ArrowLeft className="w-5 h-5" />
                    </button>
                    <div>
                        <h1 className="text-xl font-black text-neutral-900 tracking-tighter uppercase italic">Stability Engine <span className="text-red-600">DLI</span></h1>
                        <p className="text-[10px] font-bold text-neutral-400 uppercase tracking-widest">Homologação de Fidelidade Visual e Paginação</p>
                    </div>
                </div>

                <div className="flex bg-neutral-100 p-1.5 rounded-2xl shadow-inner gap-1">
                    {[
                        { id: 'all', label: 'Todos', icon: Layout },
                        { id: 'black', label: 'Black', icon: Monitor },
                        { id: 'cinematic', label: 'Cinematic', icon: Monitor },
                        { id: 'executive', label: 'Executive', icon: Monitor },
                        { id: 'corporate', label: 'Corporate', icon: Monitor }
                    ].map((mode) => (
                        <button
                            key={mode.id}
                            onClick={() => setPreviewMode(mode.id as any)}
                            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${previewMode === mode.id
                                ? 'bg-black text-white shadow-lg'
                                : 'text-neutral-500 hover:bg-neutral-200'
                                }`}
                        >
                            <mode.icon className="w-3.5 h-3.5" />
                            {mode.label}
                        </button>
                    ))}
                </div>

                <div className="text-right flex flex-col items-end">
                    <p className="text-[9px] font-bold text-neutral-400 uppercase tracking-widest mb-1">DLI Sugestão Automática:</p>
                    <span className="px-3 py-1 bg-red-600 text-white rounded-full text-[9px] font-black uppercase tracking-widest">
                        {dliSuggested} Edition
                    </span>
                </div>
            </div>

            {/* Container do Preview */}
            <div className="flex-1 space-y-20 pb-40">
                {(previewMode === 'all' || previewMode === 'black') && (
                    <div className="flex flex-col items-center gap-4">
                        <h2 className="text-xs font-black uppercase tracking-[0.5em] text-neutral-400 border-b-2 border-black/5 pb-2">Black Edition (Exemplar I)</h2>
                        <div className="scale-90 lg:scale-100 origin-top bg-white p-4 rounded-3xl shadow-2xl">
                            <BlackEdition proposal={selectedProposal} />
                        </div>
                    </div>
                )}

                {(previewMode === 'all' || previewMode === 'cinematic') && (
                    <div className="flex flex-col items-center gap-4">
                        <h2 className="text-xs font-black uppercase tracking-[0.5em] text-neutral-400 border-b-2 border-black/5 pb-2">Cinematic Edition (Exemplar II)</h2>
                        <div className="scale-90 lg:scale-100 origin-top bg-white p-4 rounded-3xl shadow-2xl">
                            <CinematicEdition proposal={selectedProposal} />
                        </div>
                    </div>
                )}

                {(previewMode === 'all' || previewMode === 'executive') && (
                    <div className="flex flex-col items-center gap-4">
                        <h2 className="text-xs font-black uppercase tracking-[0.5em] text-neutral-400 border-b-2 border-black/5 pb-2">Executive Clean (Exemplar III)</h2>
                        <div className="scale-90 lg:scale-100 origin-top bg-white p-4 rounded-3xl shadow-2xl">
                            <ExecutiveClean proposal={selectedProposal} />
                        </div>
                    </div>
                )}

                {(previewMode === 'all' || previewMode === 'corporate') && (
                    <div className="flex flex-col items-center gap-4">
                        <h2 className="text-xs font-black uppercase tracking-[0.5em] text-neutral-400 border-b-2 border-black/5 pb-2">Corporate Gold (Auto-Generated)</h2>
                        <div className="scale-90 lg:scale-100 origin-top bg-white p-4 rounded-3xl shadow-2xl">
                            <CorporateGold proposal={selectedProposal} />
                        </div>
                    </div>
                )}
            </div>

            {/* Print Instructions */}
            <div className="fixed bottom-8 right-8 bg-black text-white px-6 py-4 rounded-3xl shadow-2xl border border-white/20 flex items-center gap-4 z-50">
                <Printer className="w-5 h-5 text-red-500 animate-pulse" />
                <div className="text-left">
                    <p className="text-[10px] font-black uppercase tracking-widest">Para Testar Impressão:</p>
                    <p className="text-[9px] text-neutral-400 font-medium">Use CTRL+P e marque "Gráficos de Segundo Plano"</p>
                </div>
            </div>

            {/* Badge de Dica Informativa */}
            <div className="fixed bottom-8 left-8 bg-white/90 backdrop-blur-md px-6 py-4 rounded-3xl shadow-2xl border border-white/40 flex items-center gap-4 z-50">
                <div className="bg-yellow-400 p-2 rounded-full">
                    <Sparkles className="w-4 h-4 text-black" />
                </div>
                <p className="text-[10px] font-bold text-neutral-800 uppercase tracking-tight">
                    Fidelidade Visual 1:1 com os <span className="text-red-600 font-black italic">Exemplares</span> da pasta PDF.
                </p>
            </div>
        </div>
    );
};

export default TestPreview;
